[project]
name = "openglv"
version = "0.1.0"
description = "A description of the openxyz project."
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "matplotlib (>=3.10.3,<4.0.0)",
    "tensorflow-datasets (>=4.9.9,<5.0.0)",
    "torch (>=2.7.1,<3.0.0)",
    "transformers (>=4.52.4,<5.0.0)",
    "openai (>=1.91.0,<2.0.0)",
    "google-genai (>=1.22.0,<2.0.0)",
    "tensorflow (>=2.19.0,<3.0.0)",
    "isort (>=6.0.1,<7.0.0)",
    "black (>=25.1.0,<26.0.0)",
    "scipy (>=1.16.0,<2.0.0)",
    "datasets (>=3.6.0,<4.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
black = "^25.1.0"
isort = "^6.0.1"
pre-commit = "^4.2.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88
