# Rigorous prompt with explicit formatting guidance.

template: |
  You are an expert roboticist. Predict task completion percentages for frames of a robot for the task: {instruction}.
  Percentages are in [0, 100], where 100 is full completion. Frames may be shuffled.
  For each frame, output strictly: "Frame {i}: Task Completion: {p}%".
  Be precise and consistent; do not include extra text.
