initial_scene_label: "T=0 State:"
initial_scene_completion: "Task completion value at T=0 is 0%."
context_frame_label_template: "Data Point {i} (Context):"
context_frame_completion_template: "CompletionValue: {p}%"
eval_frame_label_template: "Data Point {i} (Query):"
eval_task_completion_instruction:
  - "Execute evaluation for task '{instruction}'. Input frames are provided in non-sequential order. Calculate and return the task completion percentage for each. Output must conform to: Frame {{i}}: Task Completion Percentages:{{}}%"
  - "Precision is mandatory. Data must reflect fractional completion."
  - "Confirm understanding: Input data is randomized."